Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -47,29 +47,36 @@ jobs:
           cd ..
           mv python-deps-layer.zip ../modules/lambda/build/python-deps-layer.zip
 
-      # ---------- Package User Migration Lambda (user-migration.zip) ----------
+     # ---------- Package User Migration Lambda (user-migration.zip) ----------
       - name: Package User Migration Lambda
         run: |
           mkdir -p modules/lambda/build
           zip -r modules/lambda/build/user-migration.zip backend/user_migration
 
-      # ---------- Deploy User Migration Lambda Function ----------
-      - name: Deploy User Migration Lambda Function
+      # ---------- Create User Migration Lambda Function if not exists ----------
+      - name: Create User Migration Lambda Function if not exists
+        run: |
+          if ! aws lambda get-function --function-name user-migration-function --region ${{ env.AWS_REGION }}; then
+          echo "Lambda function does not exist. Creating..."
+          aws lambda create-function \
+          --function-name user-migration-function \
+          --runtime python3.12 \
+          --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHubActions-StockWishlist-Role \
+          --handler user_migration.lambda_handler \
+          --zip-file fileb://modules/lambda/build/user-migration.zip \
+          --region ${{ env.AWS_REGION }}
+          else
+            echo "Lambda function already exists."
+          fi
+
+      # ---------- Update User Migration Lambda Function ----------
+      - name: Update User Migration Lambda Function
         run: |
           if [ ! -f modules/lambda/build/user-migration.zip ]; then
-          echo "Error: user-migration.zip not found!"
+            echo "Error: user-migration.zip not found!"
           exit 1
           fi
 
-          aws lambda update-function-code \
-          --function-name user-migration-function \
-          --zip-file fileb://modules/lambda/build/user-migration.zip \
-          --region ${{ env.AWS_REGION }}
-
-
-      # ---------- Deploy User Migration Lambda Function ----------
-      - name: Deploy User Migration Lambda Function
-        run: |
           aws lambda update-function-code \
           --function-name user-migration-function \
           --zip-file fileb://modules/lambda/build/user-migration.zip \
